[phases.setup]
nixPkgs = ["nodejs_22", "bun"]
nixpkgsArchive = "master"

[phases.install]
dependsOn = ["setup"]
commands = ["bun install"]

[phases.build]
commands = ["bun run build"]

[start]
cmd = "bun run start"
